export const FETCH_GIVEAWAYS = "FETCH_GIVEAWAYS";
export const DELETE_SINGLE_GIVEAWAY = "DELETE_SINGLE_GIVEAWAY";
export const TOTAL_GIVEAWAYS = "TOTAL_GIVEAWAYS";
export const DELETE_GIVEAWAYS = "DELETE_GIVEAWAYS";

export const SHOW_HIDE_FAB = "SHOW_HIDE_FAB";
export const STICKY_FAB = "STICKY_FAB";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const USER_DETAILS = "USER_DETAILS";
