export const FETCH_GIVEAWAYS = "FETCH_GIVEAWAYS";
export const DELETE_GIVEAWAY = "DELETE_GIVEAWAY";
export const TOTAL_GIVEAWAYS = "TOTAL_GIVEAWAYS";
export const DELETE_GIVEAWAYS = "DELETE_GIVEAWAYS";
