export const FETCH_GIVEAWAYS = "FETCH_GIVEAWAYS";
export const DELETE_SINGLE_GIVEAWAY = "DELETE_SINGLE_GIVEAWAY";
export const TOTAL_GIVEAWAYS = "TOTAL_GIVEAWAYS";
export const DELETE_GIVEAWAYS = "DELETE_GIVEAWAYS";
